const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const User = require('../models/User');
const Recipe = require('../models/Recipe');

const SAMPLE_RECIPES = [
  {
    title: 'Butter Chicken',
    description: 'Creamy, rich North Indian chicken curry in a tomato-based sauce, perfect for a cosy dinner.',
    ingredients: [
      { name: 'Chicken', amount: '500', unit: 'g' },
      { name: 'Butter', amount: '3', unit: 'tbsp' },
      { name: 'Heavy Cream', amount: '100', unit: 'ml' },
      { name: 'Tomato Puree', amount: '200', unit: 'ml' },
      { name: 'Onion', amount: '2', unit: 'medium' },
      { name: 'Garlic', amount: '6', unit: 'cloves' },
      { name: 'Ginger', amount: '1', unit: 'inch' },
      { name: 'Garam Masala', amount: '1', unit: 'tsp' },
      { name: 'Kashmiri Red Chili', amount: '1', unit: 'tsp' },
      { name: 'Salt', amount: 'as needed', unit: 'to taste' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Marinate chicken with yogurt, spices, and salt for 30 minutes.' },
      { stepNumber: 2, instruction: 'Grill or pan-fry the chicken until cooked through. Set aside.' },
      { stepNumber: 3, instruction: 'In a pan, melt butter and sauté onions until golden.' },
      { stepNumber: 4, instruction: 'Add garlic and ginger paste. Cook for 2 minutes.' },
      { stepNumber: 5, instruction: 'Add tomato puree and cook until oil separates.' },
      { stepNumber: 6, instruction: 'Blend the sauce smooth. Return to pan, add cream.' },
      { stepNumber: 7, instruction: 'Add chicken, simmer 10 minutes. Garnish with cream and coriander.' },
    ],
    cookingTime: { prep: 40, cook: 30, total: 70 },
    difficulty: 'Medium',
    cuisine: 'Indian',
    dietType: 'non-veg',
    servings: 4,
    tags: ['curry', 'chicken', 'indian', 'creamy'],
    nutrition: { calories: 450, protein: 35, carbs: 12, fat: 28, fiber: 2 },
    image: { url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800', alt: 'Butter Chicken' },
  },
  {
    title: 'Paneer Tikka',
    description: 'Smoky, charred Indian cottage cheese marinated in spiced yogurt and grilled to perfection.',
    ingredients: [
      { name: 'Paneer', amount: '300', unit: 'g' },
      { name: 'Yogurt', amount: '100', unit: 'ml' },
      { name: 'Bell Pepper', amount: '2', unit: 'medium' },
      { name: 'Onion', amount: '1', unit: 'large' },
      { name: 'Tikka Masala', amount: '2', unit: 'tbsp' },
      { name: 'Oil', amount: '2', unit: 'tbsp' },
      { name: 'Lemon Juice', amount: '1', unit: 'tbsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Mix yogurt with tikka masala, oil, lemon juice, and salt.' },
      { stepNumber: 2, instruction: 'Cut paneer, peppers, and onion into cubes. Coat with marinade.' },
      { stepNumber: 3, instruction: 'Marinate for at least 30 minutes.' },
      { stepNumber: 4, instruction: 'Thread onto skewers alternating paneer and vegetables.' },
      { stepNumber: 5, instruction: 'Grill or bake at 220°C for 15-20 minutes until charred.' },
      { stepNumber: 6, instruction: 'Serve with mint chutney and lemon wedges.' },
    ],
    cookingTime: { prep: 35, cook: 20, total: 55 },
    difficulty: 'Easy',
    cuisine: 'Indian',
    dietType: 'veg',
    servings: 4,
    tags: ['paneer', 'tikka', 'grilled', 'starter', 'vegetarian'],
    nutrition: { calories: 280, protein: 18, carbs: 10, fat: 18, fiber: 3 },
    image: { url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800', alt: 'Paneer Tikka' },
  },
  {
    title: 'Aglio e Olio',
    description: 'Classic Neapolitan pasta with garlic, olive oil, and chili flakes — simple, quick, and utterly delicious.',
    ingredients: [
      { name: 'Spaghetti', amount: '400', unit: 'g' },
      { name: 'Olive Oil', amount: '6', unit: 'tbsp' },
      { name: 'Garlic', amount: '8', unit: 'cloves' },
      { name: 'Red Chili Flakes', amount: '1', unit: 'tsp' },
      { name: 'Parsley', amount: '1', unit: 'handful' },
      { name: 'Parmesan', amount: '50', unit: 'g', optional: true },
      { name: 'Salt', amount: 'as needed', unit: 'to taste' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Cook spaghetti in well-salted boiling water until al dente. Reserve 1 cup pasta water.' },
      { stepNumber: 2, instruction: 'While pasta cooks, slice garlic thinly.' },
      { stepNumber: 3, instruction: 'Heat olive oil in a large pan over medium-low heat. Add garlic.' },
      { stepNumber: 4, instruction: 'Cook garlic until lightly golden (not brown). Add chili flakes.' },
      { stepNumber: 5, instruction: 'Add drained pasta and pasta water. Toss vigorously to emulsify.' },
      { stepNumber: 6, instruction: 'Add parsley, season, and serve with Parmesan.' },
    ],
    cookingTime: { prep: 5, cook: 20, total: 25 },
    difficulty: 'Easy',
    cuisine: 'Italian',
    dietType: 'veg',
    servings: 4,
    tags: ['pasta', 'quick', 'italian', 'garlic', 'easy'],
    nutrition: { calories: 380, protein: 12, carbs: 58, fat: 14, fiber: 3 },
    image: { url: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800', alt: 'Aglio e Olio pasta' },
  },
  {
    title: 'Masala Chai',
    description: 'Aromatic Indian spiced tea with ginger, cardamom, and cloves — the ultimate comfort drink.',
    ingredients: [
      { name: 'Milk', amount: '500', unit: 'ml' },
      { name: 'Water', amount: '300', unit: 'ml' },
      { name: 'Tea Leaves', amount: '2', unit: 'tsp' },
      { name: 'Ginger', amount: '1', unit: 'inch' },
      { name: 'Cardamom', amount: '4', unit: 'pods' },
      { name: 'Cloves', amount: '3', unit: 'whole' },
      { name: 'Cinnamon', amount: '1', unit: 'stick' },
      { name: 'Sugar', amount: '2', unit: 'tsp' },
    ],
    steps: [
      { stepNumber: 1, instruction: 'Crush ginger, cardamom, cloves, and cinnamon with a mortar.' },
      { stepNumber: 2, instruction: 'Boil water with the spices for 2 minutes.' },
      { stepNumber: 3, instruction: 'Add tea leaves and simmer for 1 minute.' },
      { stepNumber: 4, instruction: 'Add milk and sugar. Bring to a boil.' },
      { stepNumber: 5, instruction: 'Lower heat, simmer 3 minutes. Strain and serve hot.' },
    ],
    cookingTime: { prep: 5, cook: 10, total: 15 },
    difficulty: 'Easy',
    cuisine: 'Indian',
    dietType: 'veg',
    servings: 2,
    tags: ['chai', 'tea', 'beverage', 'quick', 'indian'],
    nutrition: { calories: 120, protein: 4, carbs: 18, fat: 4, fiber: 0 },
    image: { url: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800', alt: 'Masala Chai' },
  },
  {
  title: 'Soya Veg Biryani',
  description: 'Juicy, aromatic biryani made with marinated soya chunks, vegetables, and long separated basmati rice cooked on dum.',
  ingredients: [
    { name: 'Soya Chunks', amount: '1', unit: 'cup' },
    { name: 'Basmati Rice', amount: '2', unit: 'cups' },
    { name: 'Carrot', amount: '1', unit: 'large' },
    { name: 'Beans', amount: '25', unit: 'g' },
    { name: 'Potatoes', amount: '2', unit: 'medium' },
    { name: 'Capsicum', amount: '0.5', unit: 'optional' },
    { name: 'Green Chillies', amount: '5', unit: 'pieces' },
    { name: 'Onions', amount: '2', unit: 'large' },
    { name: 'Mint Leaves', amount: '50', unit: 'g' },
    { name: 'Coriander Leaves', amount: '100', unit: 'g' },
    { name: 'Curd', amount: '0.33', unit: 'cup' },
    { name: 'Ginger Garlic Paste', amount: '1', unit: 'tbsp' },
    { name: 'Turmeric Powder', amount: '0.5', unit: 'tsp' },
    { name: 'Red Chilli Powder', amount: '1', unit: 'tsp' },
    { name: 'Biryani Masala', amount: '1.5', unit: 'tsp' },
    { name: 'Kasuri Methi', amount: '1', unit: 'tsp' },
    { name: 'Salt', amount: 'as needed', unit: 'to taste' },
    { name: 'Bay Leaf', amount: '1', unit: 'piece' },
    { name: 'Cardamom', amount: '3', unit: 'pieces' },
    { name: 'Cloves', amount: '3', unit: 'pieces' },
    { name: 'Black Peppercorns', amount: '5', unit: 'pieces' },
    { name: 'Lemon', amount: '0.5', unit: 'piece' },
    { name: 'Milk', amount: '0.5', unit: 'cup' },
    { name: 'Saffron', amount: 'as needed', unit: 'few strands' },
    { name: 'Ghee', amount: 'as needed', unit: 'as needed' },
    { name: 'Kewra Water', amount: 'as needed', unit: 'few drops' }
  ],
  steps: [
    { stepNumber: 1, instruction: 'Soak soya chunks in boiling water for 10–15 minutes, then squeeze out excess water.' },
    { stepNumber: 2, instruction: 'Marinate soya and vegetables with curd, spices, and herbs. Rest for 20–30 minutes.' },
    { stepNumber: 3, instruction: 'Wash and soak basmati rice for 30 minutes.' },
    { stepNumber: 4, instruction: 'Boil rice with whole spices, salt, and lemon until 90% cooked. Drain and cool.' },
    { stepNumber: 5, instruction: 'Fry sliced onions until golden (birsta) and set aside.' },
    { stepNumber: 6, instruction: 'Cook marinated soya and vegetables until potatoes are soft and mixture thickens.' },
    { stepNumber: 7, instruction: 'Layer cooked vegetables and rice. Add saffron milk, fried onions, herbs, and ghee.' },
    { stepNumber: 8, instruction: 'Seal and cook on low flame (dum) for 20 minutes using a tawa. Rest before serving.' }
  ],
  cookingTime: { prep: 40, cook: 40, total: 80 },
  difficulty: 'Medium',
  cuisine: 'Indian',
  dietType: 'veg',
  servings: 4,
  tags: ['biryani', 'soya', 'rice', 'indian', 'veg'],
  nutrition: { calories: 420, protein: 18, carbs: 60, fat: 12, fiber: 6 },
  image: { url: 'http://localhost:5000/images/recipes/vb.png', alt: 'Soya Veg Biryani' },
},
{
  title: 'Soya Chilli',
  description: 'Crispy fried soya chunks tossed in a spicy Indo-Chinese sauce with garlic, onions, and capsicum.',
  ingredients: [
    { name: 'Soya Chunks', amount: '2', unit: 'cups' },
    { name: 'Water', amount: '1', unit: 'litre' },
    { name: 'Salt', amount: 'as needed', unit: 'to taste' },
    { name: 'Sugar', amount: '1', unit: 'tsp' },
    { name: 'Vinegar', amount: '2', unit: 'tsp' },
    { name: 'Garlic', amount: '6', unit: 'cloves' },
    { name: 'Ginger', amount: '1.5', unit: 'inch' },
    { name: 'Corn Starch', amount: '3', unit: 'tbsp' },
    { name: 'Maida', amount: '2', unit: 'tbsp' },
    { name: 'Chilli Garlic Sauce', amount: '2', unit: 'tsp' },
    { name: 'Black Pepper', amount: '1', unit: 'tsp' },
    { name: 'Onion', amount: '1', unit: 'large' },
    { name: 'Capsicum', amount: '1', unit: 'medium' },
    { name: 'Green Chillies', amount: '4', unit: 'pieces' },
    { name: 'Soy Sauce', amount: '1', unit: 'tbsp' },
    { name: 'Tomato Ketchup', amount: '2', unit: 'tbsp' },
    { name: 'Oil', amount: 'as needed', unit: 'for frying' },
    { name: 'Spring Onion', amount: '1', unit: 'for garnish' },
    { name: 'Coriander Leaves', amount: 'as needed', unit: 'for garnish' }
  ],
  steps: [
    { stepNumber: 1, instruction: 'Boil soya chunks with salt, sugar, vinegar, garlic, and ginger for 2–3 minutes. Drain and cool.' },
    { stepNumber: 2, instruction: 'Squeeze excess water from soya chunks.' },
    { stepNumber: 3, instruction: 'Mix soya with sauces, spices, corn starch, and maida to coat evenly.' },
    { stepNumber: 4, instruction: 'Deep fry on high flame until crispy and golden.' },
    { stepNumber: 5, instruction: 'Heat oil in a wok. Add garlic, ginger, onions, capsicum, and green chillies. Stir-fry on high heat.' },
    { stepNumber: 6, instruction: 'Add soy sauce, chilli sauce, vinegar, ketchup, salt, and pepper. Add water and simmer.' },
    { stepNumber: 7, instruction: 'Add corn starch slurry to thicken the sauce.' },
    { stepNumber: 8, instruction: 'Turn off flame and toss fried soya with sauce. Garnish and serve immediately.' }
  ],
  cookingTime: { prep: 25, cook: 20, total: 45 },
  difficulty: 'Medium',
  cuisine: 'Indo-Chinese',
  dietType: 'veg',
  servings: 4,
  tags: ['soya', 'chilli', 'indo-chinese', 'starter', 'crispy'],
  nutrition: { calories: 300, protein: 20, carbs: 25, fat: 12, fiber: 5 },
  image: { url: 'http://localhost:5000/images/recipes/sc.png', alt: 'Soya Chilli' },
},
{
  title: 'Kadai Paneer',
  description: 'Restaurant-style Kadai Paneer made with a special two-texture gravy and freshly roasted kadai masala.',
  ingredients: [
    { name: 'Paneer', amount: '400', unit: 'g' },
    { name: 'Onions', amount: '3', unit: 'medium' },
    { name: 'Tomatoes', amount: '4', unit: 'medium' },
    { name: 'Capsicum', amount: '1', unit: 'medium' },
    { name: 'Green Chillies', amount: '3', unit: 'pieces' },
    { name: 'Cashews', amount: '12', unit: 'pieces' },
    { name: 'Coriander Seeds', amount: '3.5', unit: 'tsp' },
    { name: 'Fennel Seeds', amount: '1', unit: 'tsp' },
    { name: 'Cumin Seeds', amount: '1.5', unit: 'tsp' },
    { name: 'Kashmiri Red Chillies', amount: '4', unit: 'pieces' },
    { name: 'Black Peppercorns', amount: '8', unit: 'pieces' },
    { name: 'Cardamom', amount: '2', unit: 'pieces' },
    { name: 'Cloves', amount: '2', unit: 'pieces' },
    { name: 'Ginger Garlic Paste', amount: '1', unit: 'tbsp' },
    { name: 'Turmeric Powder', amount: '0.5', unit: 'tsp' },
    { name: 'Garam Masala', amount: '0.5', unit: 'tsp' },
    { name: 'Kasuri Methi', amount: '1', unit: 'tsp' },
    { name: 'Fresh Cream', amount: 'as needed', unit: 'as needed' },
    { name: 'Butter', amount: 'as needed', unit: 'as needed' },
    { name: 'Oil', amount: 'as needed', unit: 'as needed' },
    { name: 'Salt', amount: 'as needed', unit: 'to taste' }
  ],
  steps: [
    { stepNumber: 1, instruction: 'Dry roast coriander, fennel, cumin, red chillies, pepper, cardamom, and cloves. Cool and grind coarsely.' },
    { stepNumber: 2, instruction: 'Sauté sliced onions in oil and butter until soft. Add tomatoes, salt, cashews, and ginger-garlic paste. Cook until mushy.' },
    { stepNumber: 3, instruction: 'Cool and blend the mixture partially coarse, then blend remaining smooth. Combine both textures.' },
    { stepNumber: 4, instruction: 'Lightly roast paneer cubes. Stir-fry onion cubes and capsicum on high flame.' },
    { stepNumber: 5, instruction: 'Heat oil, add cumin seeds, coriander seeds, and dried red chilli. Add turmeric and prepared gravy.' },
    { stepNumber: 6, instruction: 'Add kadai masala and cook the gravy.' },
    { stepNumber: 7, instruction: 'Add paneer, vegetables, kasuri methi, garam masala, salt, and cream.' },
    { stepNumber: 8, instruction: 'Simmer for 5 minutes, garnish with coriander and ginger juliennes, and serve.' }
  ],
  cookingTime: { prep: 30, cook: 30, total: 60 },
  difficulty: 'Medium',
  cuisine: 'Indian',
  dietType: 'veg',
  servings: 4,
  tags: ['paneer', 'kadai', 'indian', 'gravy'],
  nutrition: { calories: 350, protein: 18, carbs: 15, fat: 25, fiber: 4 },
  image: { url: 'http://localhost:5000/images/recipes/mp.png', alt: 'Kadai Paneer' },
},
{
  title: 'Matar Ki Sabzi',
  description: 'Unique pea curry made with steamed besan-pea bites cooked in a rich onion-tomato gravy.',
  ingredients: [
    { name: 'Green Peas', amount: '1.5', unit: 'cups' },
    { name: 'Besan', amount: '0.25', unit: 'cup' },
    { name: 'Garlic', amount: '10', unit: 'cloves' },
    { name: 'Ginger', amount: '2', unit: 'inch' },
    { name: 'Green Chillies', amount: '2', unit: 'pieces' },
    { name: 'Cumin Seeds', amount: '1', unit: 'tsp' },
    { name: 'Coriander Seeds', amount: '1', unit: 'tsp' },
    { name: 'Turmeric Powder', amount: '1', unit: 'tsp' },
    { name: 'Ajwain', amount: '0.25', unit: 'tsp' },
    { name: 'Onions', amount: '2', unit: 'medium' },
    { name: 'Tomatoes', amount: '3', unit: 'medium' },
    { name: 'Cloves', amount: '2', unit: 'pieces' },
    { name: 'Cardamom', amount: '2', unit: 'pieces' },
    { name: 'Bay Leaf', amount: '1', unit: 'piece' },
    { name: 'Kashmiri Red Chilli Powder', amount: '0.5', unit: 'tsp' },
    { name: 'Coriander Powder', amount: '2', unit: 'tsp' },
    { name: 'Garam Masala', amount: '0.5', unit: 'tsp' },
    { name: 'Kasuri Methi', amount: '1', unit: 'tsp' },
    { name: 'Mustard Oil', amount: 'as needed', unit: 'as needed' },
    { name: 'Salt', amount: 'as needed', unit: 'to taste' },
    { name: 'Fresh Coriander Leaves', amount: 'as needed', unit: 'for garnish' }
  ],
  steps: [
    { stepNumber: 1, instruction: 'Blend peas, besan, garlic, ginger, chillies, and water into a thick paste. Mix spices and coriander.' },
    { stepNumber: 2, instruction: 'Spread mixture in a greased plate and steam for 15 minutes. Cool and cut into pieces.' },
    { stepNumber: 3, instruction: 'Blend steamed tomatoes, garlic, ginger, and red chillies into a puree.' },
    { stepNumber: 4, instruction: 'Heat mustard oil, add whole spices and sauté onions until golden.' },
    { stepNumber: 5, instruction: 'Add turmeric, chilli powder, and tomato puree. Cook until oil separates.' },
    { stepNumber: 6, instruction: 'Add water and bring to a boil.' },
    { stepNumber: 7, instruction: 'Add pea bites, garam masala, kasuri methi, and cook briefly.' },
    { stepNumber: 8, instruction: 'Rest covered for 5 minutes, garnish, and serve.' }
  ],
  cookingTime: { prep: 35, cook: 30, total: 65 },
  difficulty: 'Medium',
  cuisine: 'Indian',
  dietType: 'veg',
  servings: 4,
  tags: ['matar', 'curry', 'indian', 'veg'],
  nutrition: { calories: 280, protein: 12, carbs: 30, fat: 12, fiber: 8 },
  image: { url: 'http://localhost:5000/images/recipes/peas.png', alt: 'Matar Ki Sabzi' },
},
{
  title: 'Aloo Matar Pulao',
  description: 'Spicy garlic-flavored pulao made with potatoes, peas, and a unique chutney base in a pressure cooker.',
  ingredients: [
    { name: 'Rice', amount: '2', unit: 'cups' },
    { name: 'Water', amount: '3', unit: 'cups' },
    { name: 'Potatoes', amount: '7', unit: 'small' },
    { name: 'Peas', amount: '1', unit: 'cup' },
    { name: 'Onion', amount: '1', unit: 'large' },
    { name: 'Tomato', amount: '2', unit: 'medium' },
    { name: 'Garlic', amount: '8', unit: 'cloves' },
    { name: 'Ginger', amount: '1', unit: 'inch' },
    { name: 'Dried Red Chillies', amount: '6', unit: 'pieces' },
    { name: 'Cumin Seeds', amount: '1', unit: 'tsp' },
    { name: 'Cinnamon Stick', amount: '1', unit: 'piece' },
    { name: 'Bay Leaf', amount: '1', unit: 'piece' },
    { name: 'Black Peppercorns', amount: '7', unit: 'pieces' },
    { name: 'Cardamom', amount: '3', unit: 'pieces' },
    { name: 'Curry Leaves', amount: '10', unit: 'pieces' },
    { name: 'Turmeric Powder', amount: '0.25', unit: 'tsp' },
    { name: 'Coriander Powder', amount: '1', unit: 'tsp' },
    { name: 'Desi Ghee', amount: '1', unit: 'tbsp' },
    { name: 'Salt', amount: 'as needed', unit: 'to taste' },
    { name: 'Green Chillies', amount: '3', unit: 'pieces' },
    { name: 'Fresh Coriander Leaves', amount: 'as needed', unit: 'for garnish' }
  ],
  steps: [
    { stepNumber: 1, instruction: 'Boil red chillies, garlic, ginger, tomato, and coriander stems. Blend into chutney.' },
    { stepNumber: 2, instruction: 'Wash rice and keep aside without soaking.' },
    { stepNumber: 3, instruction: 'Heat oil in cooker and add whole spices and curry leaves.' },
    { stepNumber: 4, instruction: 'Add onions and sauté until translucent. Add tomatoes and cook briefly.' },
    { stepNumber: 5, instruction: 'Add chutney, turmeric, salt, and coriander powder. Cook until oil separates.' },
    { stepNumber: 6, instruction: 'Add potatoes, peas, and sauté briefly.' },
    { stepNumber: 7, instruction: 'Add rice, green chillies, ghee, and mix gently.' },
    { stepNumber: 8, instruction: 'Add water and pressure cook for 2 whistles. Fluff and serve.' }
  ],
  cookingTime: { prep: 25, cook: 25, total: 50 },
  difficulty: 'Easy',
  cuisine: 'Indian',
  dietType: 'veg',
  servings: 4,
  tags: ['pulao', 'rice', 'aloo', 'matar'],
  nutrition: { calories: 320, protein: 8, carbs: 55, fat: 8, fiber: 6 },
  image: { url: 'http://localhost:5000/images/recipes/image  .png', alt: 'Aloo Matar Pulao' },
},
{
  title: 'Veg Chowmein',
  description: 'Street-style smoky veg chowmein made in a hot wok with a final coal smoking technique for authentic flavor.',
  ingredients: [
    { name: 'Noodles', amount: '500', unit: 'g' },
    { name: 'Water', amount: '2', unit: 'litre' },
    { name: 'Salt', amount: '2', unit: 'tbsp' },
    { name: 'Oil', amount: 'as needed', unit: 'as needed' },
    { name: 'Garlic', amount: '10', unit: 'cloves' },
    { name: 'Green Chillies', amount: '4', unit: 'pieces' },
    { name: 'Onions', amount: '2', unit: 'medium' },
    { name: 'Spring Onion', amount: '3', unit: 'stalks' },
    { name: 'Capsicum', amount: '1', unit: 'medium' },
    { name: 'Carrot', amount: '1', unit: 'medium' },
    { name: 'Cabbage', amount: '0.5', unit: 'medium' },
    { name: 'Dark Soy Sauce', amount: '2', unit: 'tsp' },
    { name: 'Red Chilli Sauce', amount: '2', unit: 'tsp' },
    { name: 'Vinegar', amount: '1', unit: 'tsp' },
    { name: 'Black Pepper', amount: '1', unit: 'tsp' },
    { name: 'Ajinomoto', amount: '0.5', unit: 'tsp' },
    { name: 'Schezwan Chutney', amount: '1', unit: 'tsp' }
  ],
  steps: [
    { stepNumber: 1, instruction: 'Boil noodles in salted water until 80% cooked. Drain, rinse, dry, and toss with oil.' },
    { stepNumber: 2, instruction: 'Prepare vegetables by slicing onions, capsicum, carrot, cabbage, and chopping garlic and chillies.' },
    { stepNumber: 3, instruction: 'Heat wok on high flame. Add oil, garlic, and chillies. Stir fry briefly.' },
    { stepNumber: 4, instruction: 'Add onions and spring onion whites. Cook for 30 seconds.' },
    { stepNumber: 5, instruction: 'Add vegetables and stir fry on high flame keeping them crunchy.' },
    { stepNumber: 6, instruction: 'Add noodles, sauces, vinegar, and schezwan chutney. Toss well.' },
    { stepNumber: 7, instruction: 'Add salt, pepper, ajinomoto, and spring onion greens. Mix well.' },
    { stepNumber: 8, instruction: 'Place hot coal in a bowl inside wok, pour oil, cover for 2 minutes for smoky flavor.' }
  ],
  cookingTime: { prep: 20, cook: 15, total: 35 },
  difficulty: 'Easy',
  cuisine: 'Indo-Chinese',
  dietType: 'veg',
  servings: 4,
  tags: ['noodles', 'chowmein', 'street-food', 'indo-chinese'],
  nutrition: { calories: 350, protein: 10, carbs: 55, fat: 10, fiber: 5 },
  image: { url: 'http://localhost:5000/images/recipes/ch.png', alt: 'Veg Chowmein' },
},
{
  title: 'Crispy French Fries',
  description: 'Bazaar-style crispy french fries made using a double frying technique for maximum crunch.',
  ingredients: [
    { name: 'Potatoes', amount: '6', unit: 'pieces' },
    { name: 'Ginger Garlic Paste', amount: '1', unit: 'tsp' },
    { name: 'Green Chilli Paste', amount: '1', unit: 'tsp' },
    { name: 'Turmeric Powder', amount: '0.5', unit: 'tsp' },
    { name: 'Corn Starch', amount: '6', unit: 'tbsp' },
    { name: 'Oil', amount: 'as needed', unit: 'for frying' },
    { name: 'Salt', amount: 'as needed', unit: 'to taste' },
    { name: 'Peri Peri Masala', amount: 'as needed', unit: 'optional' }
  ],
  steps: [
    { stepNumber: 1, instruction: 'Peel and cut potatoes into uniform sticks. Do not wash after cutting.' },
    { stepNumber: 2, instruction: 'Mix potatoes with ginger garlic paste, chilli paste, and turmeric.' },
    { stepNumber: 3, instruction: 'Add corn starch in batches to coat evenly.' },
    { stepNumber: 4, instruction: 'Fry on medium heat for 4–5 minutes until half cooked. Rest for 2–3 minutes.' },
    { stepNumber: 5, instruction: 'Fry again on high heat until golden and crispy.' },
    { stepNumber: 6, instruction: 'Sprinkle salt and peri peri masala. Serve hot.' }
  ],
  cookingTime: { prep: 15, cook: 15, total: 30 },
  difficulty: 'Easy',
  cuisine: 'Fast Food',
  dietType: 'veg',
  servings: 3,
  tags: ['fries', 'snack', 'crispy', 'fast-food'],
  nutrition: { calories: 300, protein: 4, carbs: 45, fat: 14, fiber: 4 },
  image: { url: 'http://localhost:5000/images/recipes/ff.png', alt: 'French Fries' },
},
{
  title: 'Suji Papad',
  description: 'Crunchy homemade papad made from semolina, dried and fried to perfection.',
  ingredients: [
    { name: 'Suji', amount: '1', unit: 'cup' },
    { name: 'Water', amount: '8', unit: 'cups' },
    { name: 'Salt', amount: '0.5', unit: 'tsp' },
    { name: 'Baking Soda', amount: '0.125', unit: 'tsp' },
    { name: 'Cumin Seeds', amount: '0.5', unit: 'tsp' },
    { name: 'Black Pepper', amount: '0.5', unit: 'tsp' },
    { name: 'Oil', amount: 'as needed', unit: 'for frying' }
  ],
  steps: [
    { stepNumber: 1, instruction: 'Boil water and add salt, baking soda, cumin, and pepper.' },
    { stepNumber: 2, instruction: 'Add suji gradually while stirring and cook until thick.' },
    { stepNumber: 3, instruction: 'Let batter cool slightly.' },
    { stepNumber: 4, instruction: 'Spread batter on plastic sheet in round shapes.' },
    { stepNumber: 5, instruction: 'Dry in shade for a day, then sun dry until crisp.' },
    { stepNumber: 6, instruction: 'Deep fry in hot oil until puffed and crispy.' }
  ],
  cookingTime: { prep: 30, cook: 20, total: 50 },
  difficulty: 'Medium',
  cuisine: 'Indian',
  dietType: 'veg',
  servings: 6,
  tags: ['papad', 'snack', 'suji', 'crispy'],
  nutrition: { calories: 200, protein: 5, carbs: 30, fat: 6, fiber: 2 },
  image: { url: 'http://localhost:5000/images/recipes/paper.png', alt: 'Suji Papad' },
}
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/quickmake');
  console.log('Connected to MongoDB');

  await User.deleteMany({});
  await Recipe.deleteMany({});
  console.log('Cleared existing data');

  // Create admin user
  const admin = await User.create({
    name: 'Quick Make Chef',
    email: 'admin@quickmake.app',
    password: 'Admin@12345',
    role: 'admin',
    bio: 'Official Quick Make chef account.',
  });
  console.log('Admin user created:', admin.email);

  // Create sample recipes
  for (const recipeData of SAMPLE_RECIPES) {
    await Recipe.create({ ...recipeData, author: admin._id });
    console.log('Created recipe:', recipeData.title);
  }

  console.log('Seeding complete!');
  process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
